
variables:
  pythonVersion: 3.11
  poetryVersion: 2.1.3
  pre_commit_version: 2.19.0
  devops_organisation: organisation_name
  devops_project: rdam
  sh_agent_pool_name: private_agent_name
  # Create booleans for branches we want to build.
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
