
parameters:
- name: python_version
  type: string
- name: pre_commit_version
  type: string

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{ parameters.python_version }}'
    displayName: 'Use Python ${{ parameters.python_version }}'
  - script: |
      python -m pip install --upgrade pip
      python -m pip install pre-commit==${{ parameters.pre_commit_version }}
    displayName: 'Install dependencies with poetry'
