
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: rdam_green_space_monitoring-deployment
endpoint_name: rdam_green_space_monitoring-online
model: azureml:rdam_green_space_monitoring:1
code_configuration:
  code: ../../aml_deployments/components/package_c
  scoring_script: package_c_script.py
environment: 
  conda_file: ../../aml_deployments/components/package_c/package_c_env.yml
  image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04
instance_type: Standard_DS3_v2
instance_count: 1
app_insights_enabled: true
egress_public_network_access: disabled
